info:
  app:
    name: Europeana Archaelogy Mapping Tool
    description: Europeana Archaelogy Mapping Tool API
    version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics, env
  info:
    git:
      mode: full
server:
  port: 8085

# For logging use logback-spring.xml
#logging:
#  level:
#    ROOT: INFO

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:${EU_ARCH_DB_PORT}/${EU_ARCH_DB_CATALOG}?autoReconnect=true&useSSL=false&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: ${EU_ARCH_DB_USERNAME}
    password: ${EU_ARCH_DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  hikari:
    minimumIdle: 1
    maximum-pool-size: 1
    idleTimeout: 10000
    poolName: "euArchaeologyDatabaseConnectionPool"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect

    hibernate:
      ddl-auto: none
      query:
        immutable_entity_update_query_handling_mode: exception
      naming:
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

# Enable multipart uploads
  servlet:
      multipart:
          enabled: true
#          file-size-threshold: 2KB
#          multipart.max-file-size: 20MB
          max-file-size: 30MB
          max-request-size: 30MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.storage-home: ${EU_ARCH_FS_STORAGE_HOME}